### PR TITLE
[Task #50002] show order detail for user and localization js

### PR DESCRIPTION
**Pull request by giangnguyen20**
## Related Tickets:
- [#50002](https://edu-redmine.sun-asterisk.vn/issues/50002)

## WHAT this PR does?
- user xem trạng thái đơn hàng.
- Đa ngôn ngữ cho js

## Notes Impacted Areas:
- N/A.

## Attachments:
- N/A.

### CODE REVIEW

**Comment by giangnguyen20** [comment]
ready

**Comment by giangnguyen20** [comment]
ready

**Comment by giangnguyen20** [comment]
ready

**Comment by giangnguyen20** [comment]
ready

**Review by hungtd-1218 — APPROVED** [review]

**Comment by giangnguyen20** [comment]
ready

**Review by nampt-1266 — APPROVED** [review]

**Pull request merged**
