### PR TITLE
[Task #51074] Register api

### PR DESCRIPTION
**Pull request by giangnguyen20**
## Related Tickets:
- [#51074](https://edu-redmine.sun-asterisk.vn/issues/51074)

## WHAT this PR does?
- Register API.

## Notes Impacted Areas:
- N/A.

## Attachments:
image
image

### CODE REVIEW

**Comment by giangnguyen20** [comment]
ready

**Review by huyenttm-0901 — COMMENTED** [review]
cmt thử nhé

**Comment by huyenttm-0901** [comment]
ready

**Comment by huyenttm-0901** [comment]
ready

**Pull request closed without merging**
